sonar.projectKey=vishal20034_InternshipManagementSystem-Final
sonar.organization=vishal20034
sonar.projectName=Internship Management System
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,uploads/**,public/**,seeds/**,attached_assets/**,artifacts/**,coverage/**,tests/**,*.min.js

sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.cpd.exclusions=tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.scm.provider=git
