// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ten-homepage/RoleConstellation.tsx": () => import("../components/mockups/ten-homepage/RoleConstellation.tsx"),
  "./components/mockups/ten-homepage/RoleTheater.tsx": () => import("../components/mockups/ten-homepage/RoleTheater.tsx"),
  "./components/mockups/ten-homepage/UnifiedNarrative.tsx": () => import("../components/mockups/ten-homepage/UnifiedNarrative.tsx")
};
