const mongoose = require('mongoose');

const paymentSchema = new mongoose.Schema({
  orderId:         { type: String, required: true, unique: true },
  invoiceRef:      { type: String, required: true },
  studentId:       { type: mongoose.Schema.Types.ObjectId, ref: 'Student' },
  employeeId:      { type: String, required: true },
  amountRupees:    { type: Number, required: true },
  amountPaisa:     { type: Number, required: true },
  currency:        { type: String, default: 'INR' },
  status:          { type: String, enum: ['pending','success','failed'], default: 'pending' },
  paymentUrl:      { type: String },
  txnUtr:          { type: String },
  txnTime:         { type: String },
  customerName:    { type: String },
  customerEmail:   { type: String },
  customerMobile:  { type: String },
  customerUpiId:   { type: String },
  webhookPayload:  { type: Object },
  autoGenerated:   { type: Boolean, default: false },
  description:     { type: String },
  createdAt:       { type: Date, default: Date.now },
  updatedAt:       { type: Date, default: Date.now }
});

module.exports = mongoose.model('Payment', paymentSchema);
